/*
  Unosimo tri nova korisnika u tabelu 'Korisnici'.
  Svaki red predstavlja jednog korisnika sa njegovim ID-jem, imenom, emailom i datumom registracije.
*/
INSERT INTO Korisnici (ID, Ime, Email, DatumRegistracije) VALUES (1, 'Petar Petrović', 'petar.petrovic@example.com', '2025-07-30');
INSERT INTO Korisnici (ID, Ime, Email, DatumRegistracije) VALUES (2, 'Jovana Jovanović', 'jovana.jovanovic@example.com', '2025-07-31');
INSERT INTO Korisnici (ID, Ime, Email, DatumRegistracije) VALUES (3, 'Marko Marković', 'marko.markovic@example.com', '2025-08-01');
